FROM java:latest
RUN echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
RUN wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
RUN apt-get update
RUN apt-get install newrelic-sysmond
RUN nrsysmond-config --set license_key=8c1b7385f48a1a903af104bf08bef96b2dc81264
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade awscli